### ISSUE TITLE
Add 1Password Beta Chrome ID

### ISSUE THREAD

**Issue by SethCalkins** [ravenac95/sudolikeaboss-workaround#2]
Failure to load 1Password Beta extension from Chrome

1Password Beta Version would be - 
`EXTENSION_NAME = "phicbbndgmmpogmijjkbmdhpioaieaha"`

**Comment by ravenac95** [comment]
@SethCalkins the workaround should not be necessary anymore actually. Try reinstalling sudolikeaboss with the latest instructions on [github.com/ravenac95/sudolikeaboss](https://github.com/ravenac95/sudolikeaboss). If that doesn't work for you let me know. I want to make sure that sudolikeaboss still works for everyone. I use it everyday so I would understand the frustration if it were broken.
